name: Build Only

on:
  workflow_dispatch:  # Manual trigger
  
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.20'
        
    - name: Restore dependencies
      run: dotnet restore YouTubeDownloader/YouTubeDownloader.csproj
      
    - name: Build application
      run: dotnet build YouTubeDownloader/YouTubeDownloader.csproj --configuration Release --no-restore
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: YouTubeDownloader-Build-${{ github.sha }}
        path: YouTubeDownloader/bin/Release/net8.0-windows/
        retention-days: 30